version: "3"
services:
  civicrm:
    image: michaelmcandrew/civicrm:5.24.5-drupal-php7.3
    hostname: mytesthostname
    links:
      - mysql  
    ports:
      - "80:80"
    environment:
      - PROJECT_NAME=civicrmtestproject
      - BASE_URL=http://mytesthostname.com
      - CIVICRM_DB_NAME=civicrm
      - CIVICRM_DB_USER=root
      - CIVICRM_DB_PASS
      - CIVICRM_DB_HOST=mysql
      - CIVICRM_DB_PORT=3306
      - DRUPAL_DB_NAME=drupal
      - DRUPAL_DB_USER=root
      - DRUPAL_DB_PASS
      - DRUPAL_DB_HOST=mysql
      - DRUPAL_DB_PORT=3306
      - PHP_DATE_TIMEZONE="UTC"
      - DEBUG=ON
      - SMTP_HOST
      - SMTP_MAILDOMAIN
    volumes:
      - files:/var/www/html/sites/default/files
      - ./state:/state
      - ./.bash_history:/home/civicrm/.bash_history
    restart: always
  maildev:
    image: djfarrelly/maildev
    restart: always
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: placeholderPass
    volumes:
      - mysql:/var/lib/mysql
    restart: unless-stopped
volumes:
  files:
  mysql:
